export const keys = {
  me: ["me"] as const,
  today: ["today"] as const,
  tasks: (filter?: string) => ["tasks", filter ?? "all"] as const,
  task: (id: string) => ["task", id] as const,
  proof: (id: string) => ["proof", id] as const,
  activeTask: ["tasks", "mine", "active"] as const,
  queue: ["tasks", "mine", "queue"] as const,
  taskPreview: (id: string) => ["tasks", "preview", id] as const,
  onboarding: ["onboarding"] as const,
  capacity: ["me", "capacity"] as const,
  reviewQueue: ["queues", "review"] as const,
  verificationQueue: ["queues", "verification"] as const,
  accounts: ["accounts"] as const,
  taskers: (certifiedFor?: string) => ["taskers", certifiedFor ?? "all"] as const,
  tasker: (id: string) => ["tasker", id] as const,
  taskerSubmissions: (id: string) => ["tasker", id, "submissions"] as const,
  taskTypes: ["task-types"] as const,
  certifications: ["me", "certifications"] as const,
  quiz: (id: string) => ["quiz", id] as const,
  audit: ["audit"] as const,
  tickets: ["tickets"] as const,
  ticket: (id: string) => ["ticket", id] as const,
  onboardingVideos: ["onboarding", "videos"] as const,
  videoStorage: ["tutorials", "storage"] as const,
  workRequests: ["work-requests"] as const,
};
